version: 2
models:
  - name: stg_column
    config:
      meta:
        hidden: true
  - name: stg_date
    config:
      meta:
        hidden: true
  - name: stg_execution
    config:
      meta:
        hidden: true
  - name: stg_exposure
    config:
      meta:
        hidden: true
  - name: stg_invocation
    config:
      meta:
        hidden: true
  - name: stg_metric
    config:
      meta:
        hidden: true
  - name: stg_model
    config:
      meta:
        hidden: true
  - name: stg_seed
    config:
      meta:
        hidden: true
  - name: stg_snapshot
    config:
      meta:
        hidden: true
  - name: stg_source
    config:
      meta:
        hidden: true
  - name: stg_test
    config:
      meta:
        hidden: true
