version: 2
models:
  - name: observability__stg_column
    config:
      meta:
        hidden: true
  - name: observability__stg_date
    config:
      meta:
        hidden: true
  - name: observability__stg_execution
    config:
      meta:
        hidden: true
  - name: observability__stg_exposure
    config:
      meta:
        hidden: true
  - name: observability__stg_invocation
    config:
      meta:
        hidden: true
  - name: observability__stg_metric
    config:
      meta:
        hidden: true
  - name: observability__stg_model
    config:
      meta:
        hidden: true
  - name: observability__stg_seed
    config:
      meta:
        hidden: true
  - name: observability__stg_snapshot
    config:
      meta:
        hidden: true
  - name: observability__stg_source
    config:
      meta:
        hidden: true
  - name: observability__stg_test
    config:
      meta:
        hidden: true
